version: "3.9"

services:
  app:
    image: cosmtrek/air
    container_name: budgestify_app_hotreload
    # working_dir value has to be the same of mapped volume
    working_dir: /project-package
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./:/project-package/
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: budgestify_mysql_db
    ports:
      - "${DB_PORT}"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
  
  phpmyadmin:
    image: phpmyadmin
    container_name: budgestify_phpmyadmin
    restart: always
    ports:
      - 7001:80
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: ${DB_PORT}
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

volumes:
  db_data:
